# Generated by Django 5.0.4 on 2024-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=3)),
                ('birthdar', models.DateField()),
                ('score', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'programmer',
            },
        ),
    ]
